// // File generated by FlutterFire CLI.
// // ignore_for_file: type=lint
// import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
// import 'package:flutter/foundation.dart'
//     show defaultTargetPlatform, kIsWeb, TargetPlatform;

// /// Default [FirebaseOptions] for use with your Firebase apps.
// ///
// /// Example:
// /// ```dart
// /// import 'firebase_options.dart';
// /// // ...
// /// await Firebase.initializeApp(
// ///   options: DefaultFirebaseOptions.currentPlatform,
// /// );
// /// ```
// class DefaultFirebaseOptions {
//   static FirebaseOptions get currentPlatform {
//     if (kIsWeb) {
//       return web;
//     }
//     switch (defaultTargetPlatform) {
//       case TargetPlatform.android:
//         return android;
//       case TargetPlatform.iOS:
//         return ios;
//       case TargetPlatform.macOS:
//         return macos;
//       case TargetPlatform.windows:
//         return windows;
//       case TargetPlatform.linux:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for linux - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       default:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions are not supported for this platform.',
//         );
//     }
//   }

//   static const FirebaseOptions web = FirebaseOptions(
//     apiKey: 'AIzaSyDuh9K7xezvfjdjMv-mmt8KiFI54qY6iow',
//     appId: '1:245842204517:web:6e11ad374577fdd20d738c',
//     messagingSenderId: '245842204517',
//     projectId: 'things-a',
//     authDomain: 'things-a.firebaseapp.com',
//     databaseURL: 'https://things-a-default-rtdb.firebaseio.com',
//     storageBucket: 'things-a.appspot.com',
//   );

//   static const FirebaseOptions android = FirebaseOptions(
//     apiKey: 'AIzaSyDkCWjkIrrNohuKDOVgwCrDjmRsIfH4UJ4',
//     appId: '1:245842204517:android:7818c97ab5e57b790d738c',
//     messagingSenderId: '245842204517',
//     projectId: 'things-a',
//     databaseURL: 'https://things-a-default-rtdb.firebaseio.com',
//     storageBucket: 'things-a.appspot.com',
//   );

//   static const FirebaseOptions ios = FirebaseOptions(
//     apiKey: 'AIzaSyCNzTpv9wcIDyQQ4IzbOZlaIcX2_hTDQYI',
//     appId: '1:245842204517:ios:555cfb1829a85bbb0d738c',
//     messagingSenderId: '245842204517',
//     projectId: 'things-a',
//     databaseURL: 'https://things-a-default-rtdb.firebaseio.com',
//     storageBucket: 'things-a.appspot.com',
//     iosBundleId: 'com.example.thingsApp',
//   );

//   static const FirebaseOptions macos = FirebaseOptions(
//     apiKey: 'AIzaSyCNzTpv9wcIDyQQ4IzbOZlaIcX2_hTDQYI',
//     appId: '1:245842204517:ios:555cfb1829a85bbb0d738c',
//     messagingSenderId: '245842204517',
//     projectId: 'things-a',
//     databaseURL: 'https://things-a-default-rtdb.firebaseio.com',
//     storageBucket: 'things-a.appspot.com',
//     iosBundleId: 'com.example.thingsApp',
//   );

//   static const FirebaseOptions windows = FirebaseOptions(
//     apiKey: 'AIzaSyDuh9K7xezvfjdjMv-mmt8KiFI54qY6iow',
//     appId: '1:245842204517:web:ed7bd8e48947523c0d738c',
//     messagingSenderId: '245842204517',
//     projectId: 'things-a',
//     authDomain: 'things-a.firebaseapp.com',
//     databaseURL: 'https://things-a-default-rtdb.firebaseio.com',
//     storageBucket: 'things-a.appspot.com',
//   );
// }
